scrape_configs:
  - job_name: 'product'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8182']
        labels:
          application: 'product'
  - job_name: 'user'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8181']
        labels:
          application: 'user'
  - job_name: 'order'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8183']
        labels:
          application: 'order'