spring:

  #spring cloud streams for kafka
  cloud:
    function:
      definition: orderCreatedEventConsumer
    stream:
      bindings:
        orderCreatedEventConsumer-in-0:
          destination: order.exchange
          group: notification-group
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092


server:
  port: 8185

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    prefer-ip-address: true
    service-url:
      defaultZone: http://eureka:8761/eureka
