spring:


  cloud:
    function:
      definition: placeOrder;paidOrders
    stream:
      bindings:
        placeOrder-out-0:
          destination: order.exchange
          content-type: application/json
        paidOrders-in-0:
          destination: payment.completed
          group: order-consumer
          content-type: application/json
      kafka:
        binder:
          brokers: kafka:9092

  datasource:
    url: ${DB_URL}/orders
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${DB_DIALECT}


server:
  port: 8183

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:8761/eureka/


# For logging
logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rolling policy:
      max-file-size: 5MB
      max-history: 7

management:
  endpoints:
    web:
      exposure:
        include: "*"

# show health details
  endpoint:
    health:
      show-details: always

# For Zipkin
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

# show health details for circuitbreaker
  health:
    circuitbreakers:
      enabled: true

# Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      product:
        register-health-indicator: true
        minimum-number-of-calls: 5
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: count_based

# For retry
  retry:
    instances:
      retryBreaker:
        max-attempts: 5
        wait-duration:
          seconds: 5s

# For rate Limiting
  ratelimiter:
    instances:
      rateLimitBreaker:
        timeout-duration:
          seconds: 0
        limit-refresh-period:
          seconds: 4
        limit-for-period: 2



